apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server | quote }}
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.0.0
    helm:
      valuesObject:
        namespaceOverride: "argocd"
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true